apiVersion: v1
kind: Service
metadata:
{{- if .Values.meta.service.annotations }}
  annotations:
{{ toYaml .Values.meta.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "influxdb-enterprise.fullname" . }}-meta
  labels:
    influxdb.influxdata.com/component: meta
    {{- include "influxdb-enterprise.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8089
    protocol: TCP
    name: raft
  - port: 8091
    protocol: TCP
    name: http
  selector:
    influxdb.influxdata.com/component: meta
    {{- include "influxdb-enterprise.selectorLabels" . | nindent 4 }}
